spring.application.name=eduapp

#server.port=8081
#server.servlet.context-path=/eduapp

# (
#   when deploying (for example) to production, run jar from terminal with prod profile:
#     java -jar eduapp.jar --spring.profiles.active=prod
# )
# (keep dev profile as fallback)
spring.profiles.active=dev

# (below lines probably not needed - driver & dialect should be auto-detected)
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
