-- V1__initial_schema.sql
-- PostgreSQL

-- =========================
-- Security / Auth tables
-- =========================
CREATE TABLE roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,

    CONSTRAINT pk_roles      PRIMARY KEY (id),
    CONSTRAINT uq_roles_name UNIQUE (name)
);

-- CREATE INDEX idx_roles_name ON roles (name); -- not needed because postgresql automatically creates a hidden backing index for every PRIMARY KEY and UNIQUE constraint

CREATE TABLE capabilities (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255) NULL,

    CONSTRAINT pk_capabilities      PRIMARY KEY (id),
    CONSTRAINT uq_capabilities_name UNIQUE (name)
);

-- CREATE INDEX idx_capabilities_name ON capabilities (name); -- not needed because postgresql automatically creates a hidden backing index for every PRIMARY KEY and UNIQUE constraint

CREATE TABLE roles_capabilities (
    role_id       BIGINT NOT NULL,
    capability_id BIGINT NOT NULL,

    CONSTRAINT pk_roles_capabilities PRIMARY KEY (role_id, capability_id),
    CONSTRAINT fk_roles_capabilities_roles
        FOREIGN KEY (role_id) REFERENCES roles (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_roles_capabilities_capabilities
        FOREIGN KEY (capability_id) REFERENCES capabilities (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_roles_capabilities_capability_id ON roles_capabilities (capability_id);

CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID         NOT NULL,
    username   VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    role_id    BIGINT       NOT NULL,

    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL,
    deleted    BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ  NULL,

    CONSTRAINT pk_users          PRIMARY KEY (id),
    CONSTRAINT uq_users_uuid     UNIQUE (uuid),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT fk_users_roles
        FOREIGN KEY (role_id) REFERENCES roles (id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_users_role_id    ON users (role_id);
CREATE INDEX idx_users_deleted    ON users (deleted);
-- CREATE INDEX idx_users_active_users ON users (id) WHERE deleted = FALSE; -- partial index is perhaps more optimal than the above index if queries frequently look for non-deleted records (and especially if the partial index is composite and also indexes another field with higher cardinality)
CREATE INDEX idx_users_deleted_at ON users (deleted_at);


-- =========================
-- Domain tables
-- =========================
CREATE TABLE regions (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,

    CONSTRAINT pk_regions      PRIMARY KEY (id),
    CONSTRAINT uq_regions_name UNIQUE (name)
);

-- CREATE INDEX idx_regions_name ON regions (name); -- not needed because postgresql automatically creates a hidden backing index for every PRIMARY KEY and UNIQUE constraint

CREATE TABLE attachments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    filename     VARCHAR(255)  NULL,
    saved_name   VARCHAR(255)  NOT NULL,
    file_path    VARCHAR(1024) NOT NULL,
    content_type VARCHAR(255)  NULL,
    extension    VARCHAR(50)   NULL,

    created_at   TIMESTAMPTZ   NOT NULL,
    updated_at   TIMESTAMPTZ   NOT NULL,
    deleted      BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at   TIMESTAMPTZ   NULL,

    CONSTRAINT pk_attachments            PRIMARY KEY (id),
    CONSTRAINT uq_attachments_saved_name UNIQUE (saved_name)
);

CREATE INDEX idx_attachments_deleted    ON attachments (deleted);
-- CREATE INDEX idx_attachments_active_attachments ON attachments (id) WHERE deleted = FALSE; -- partial index is perhaps more optimal than the above index if queries frequently look for non-deleted records (and especially if the partial index is composite and also indexes another field with higher cardinality)
CREATE INDEX idx_attachments_deleted_at ON attachments (deleted_at);

CREATE TABLE personal_information (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amka                         VARCHAR(255) NOT NULL,
    identity_number              VARCHAR(255) NOT NULL,
    place_of_birth               VARCHAR(255) NOT NULL,
    municipality_of_registration VARCHAR(255) NOT NULL,
    amka_file_id                 BIGINT       NULL,

    created_at                   TIMESTAMPTZ  NOT NULL,
    updated_at                   TIMESTAMPTZ  NOT NULL,
    deleted                      BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at                   TIMESTAMPTZ  NULL,

    CONSTRAINT pk_personal_information                  PRIMARY KEY (id),
    CONSTRAINT uq_personal_information_amka             UNIQUE (amka),
    CONSTRAINT uq_personal_information_identity_number  UNIQUE (identity_number),
    CONSTRAINT uq_personal_information_amka_file_id     UNIQUE (amka_file_id),
    CONSTRAINT fk_personal_information_attachments
        FOREIGN KEY (amka_file_id) REFERENCES attachments (id)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

CREATE INDEX idx_personal_information_deleted    ON personal_information (deleted);
-- CREATE INDEX idx_personal_information_active_personal_information ON personal_information (id) WHERE deleted = FALSE; -- partial index is perhaps more optimal than the above index if queries frequently look for non-deleted records (and especially if the partial index is composite and also indexes another field with higher cardinality)
CREATE INDEX idx_personal_information_deleted_at ON personal_information (deleted_at);

CREATE TABLE teachers (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid             UUID         NOT NULL,
    firstname        VARCHAR(255) NOT NULL,
    lastname         VARCHAR(255) NOT NULL,
    vat              VARCHAR(255) NOT NULL,
    region_id        BIGINT       NULL,
    user_id          BIGINT       NOT NULL,
    personal_info_id BIGINT       NULL,

    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL,
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at       TIMESTAMPTZ  NULL,

    CONSTRAINT pk_teachers                  PRIMARY KEY (id),
    CONSTRAINT uq_teachers_uuid             UNIQUE (uuid),
    CONSTRAINT uq_teachers_vat              UNIQUE (vat),
    CONSTRAINT uq_teachers_user_id          UNIQUE (user_id), -- enforce 1-1
    CONSTRAINT uq_teachers_personal_info_id UNIQUE (personal_info_id), -- enforce 1-1

    CONSTRAINT fk_teachers_regions
        FOREIGN KEY (region_id) REFERENCES regions (id)
        ON DELETE SET NULL
        ON UPDATE CASCADE,
    CONSTRAINT fk_teachers_users
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CONSTRAINT fk_teachers_personal_information
        FOREIGN KEY (personal_info_id) REFERENCES personal_information (id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE INDEX idx_teachers_region_id        ON teachers (region_id);
CREATE INDEX idx_teachers_lastname         ON teachers (lastname);
CREATE INDEX idx_teachers_deleted          ON teachers (deleted);
-- CREATE INDEX idx_teachers_active_teachers ON teachers (id) WHERE deleted = FALSE; -- partial index is perhaps more optimal than the above index if queries frequently look for non-deleted records (and especially if the partial index is composite and also indexes another field with higher cardinality)
CREATE INDEX idx_teachers_deleted_at       ON teachers (deleted_at);
-- CREATE INDEX idx_teachers_user_id          ON teachers (user_id); -- not needed because postgresql automatically creates a hidden backing index for every PRIMARY KEY and UNIQUE constraint
-- CREATE INDEX idx_teachers_personal_info_id ON teachers (personal_info_id); -- not needed because postgresql automatically creates a hidden backing index for every PRIMARY KEY and UNIQUE constraint

